name: matches
description: Utility classes that are useful already, but will become even more useful when Dart 3 arrives
version: 0.1.4+9
repository: https://github.com/lesnitsky/matches

environment:
  sdk: ">=2.19.2 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
