name: dart_patterns
description: Collection of useful patterns for Dart
version: 0.3.0
repository: https://github.com/lesnitsky/dart_patterns

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.2
